📝 update

diff --git a/Taskfile b/Taskfile
--- a/Taskfile
+++ b/Taskfile
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
-# PATH=./node_modules/.bin:$PATH
-# https://www.tldp.org/LDP/abs/html/options.html
+#/ PATH=./node_modules/.bin:$PATH
+#/ https://www.tldp.org/LDP/abs/html/options.html
 # Similar to -v (Print each command to stdout before executing it), but expands commands
-set -o xtrace
+# set -o xtrace
 # set -o verbose
 # Abort script at first error, when a command exits with non-zero status (except in until or while loops, if-tests, list constructs)
 set -o errexit
@@ -10,6 +10,8 @@ set -o errexit
 set -o pipefail
 # Attempt to use undefined variable outputs error message, and forces an exit
 set -o nounset
+# makes iterations and splitting less surprising
+IFS=$'\n\t'
 # full path current folder
 __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 # full path of the script.sh (including the name)
@@ -18,6 +20,31 @@ __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
 __base="$(basename ${__file} .sh)"
 # full path of the parent folder
 __root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app
+
+# Log function
+# This disables and re-enables debug trace mode (only if it was already set)
+# Sources: https://superuser.com/a/1338887/922762 --  https://github.com/Kurento/adm-scripts/blob/master/bash.conf.sh
+shopt -s expand_aliases  # This trick requires enabling aliases in Bash
+BASENAME="$(basename "$0")"  # Complete file name
+echo_and_restore() {
+    echo "[${BASENAME}] $(cat -)"
+    # shellcheck disable=SC2154
+    case "$flags" in (*x*) set -x; esac
+}
+alias log='({ flags="$-"; set +x; } 2>/dev/null; echo_and_restore) <<<'
+
+
+# Exit trap
+# This runs at the end or, thanks to 'errexit', upon any error
+on_exit() {
+    { _RC="$?"; set +x; } 2>/dev/null
+    if ((_RC)); then log "ERROR ($_RC)"; else log "SUCCESS"; fi
+    log "#################### END ####################"
+}
+trap on_exit EXIT
+
+
+log "==================== BEGIN ===================="
 
 export appdir="$__dir"/src/fsdict
 export SOURCE_FILES="$appdir tests"
@@ -72,8 +99,7 @@ function update () {
 }
 
 function install {
-    assert_env
-    pip install -e .
+    echo "install task not implemented"
 }
 
 function lint () {
@@ -88,9 +114,9 @@ function lint () {
 
 function report () {
     echo "Flake8 report:" > "$__dir"/code_report.txt
-    flake8 "$__dir"/"$appdir" >> code_report.txt
+    flake8 "$appdir" >> code_report.txt
     echo "Bandit report:" >> code_report.txt
-    bandit -r "$__dir"/"$appdir" >> "$__dir"/code_report.txt
+    bandit -r "$appdir" >> "$__dir"/code_report.txt
 }
 
 function publish () {
@@ -109,8 +135,14 @@ function publish () {
 
     clean
 
+    log "building package"
     python3 setup.py sdist bdist_wheel
+
+    log "uploading to PyPi"
+
     python3 -m twine upload dist/*
+
+    log "cleaning..."
     clean
 
     echo "You probably want to also tag the version now:"
@@ -120,10 +152,30 @@ function publish () {
 }
 
 
+function build () {
+    echo "build task not implemented"
+}
+
 function tester () {
     echo "not implemented"
     assert_env
     # pytest ...
+}
+
+function buildprod {
+    echo "build task not implemented"
+    assert_env
+    # this runs in parallel
+    format & deps & tester & 
+    wait
+    echo "not implemented"
+    # shiv ...
+}
+
+function start {
+    echo "running app with uvicorn"
+    assert_env
+    uvicorn --workers 2 app.main:app --reload --reload-dir "$appdir"
 }
 
 function default {
@@ -131,11 +183,15 @@ function default {
     clean
 }
 
-function help {
+function tasks {
     echo "$0 <task> <args>"
     echo "Tasks:"
     compgen -A function | cat -n
 }
 
+# Help message (extracted from script headers)
+usage() { grep '^#/' "$0" | cut --characters=4-; exit 0; }
+REGEX='(^|\W)(-h|--help)($|\W)'
+[[ "$*" =~ $REGEX ]] && usage || true
 TIMEFORMAT="Task completed in %3lR"
 time ${@:-default}
